### ISSUE TITLE
False positive on Structural Type

### ISSUE THREAD

**Issue by ngbinh** [scalastyle/scalastyle#180]
Shapeless does not use reflection or structural type but scalastyle complains that this line
https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/ops/hlists.scala#L777
uses structural typing. 

Even though it is a structural type from a typechecking point of view, but it's completely erased at runtime, so there's no cost at all.

**Comment by milessabin** [comment]
Just to clarify, I don't think there's any structural typing on that line at all, erased or otherwise. More generally, if you could try and detect type-lambdas and not report them as incurring runtime reflection overhead that would be great.

**Comment by matthewfarwell** [comment]
I'm not sure I can, actually. The StructuralTypeChecker detects Refinements, it is very simple.

I would have to understand this is a lot more depth to know how to fix this. Also, I'm not sure how much effort I want to put into this given that the Scala compiler also detects Structural types, and a lot better than Scalastyle.

My tendancy is to close this. Is this something you're really attached to?

**Comment by milessabin** [comment]
The problem here is that the presence of a refinement doesn't imply that there will be any form of reflective structural access to value members at run time, so the error report is incorrect. All uses of type lambdas or the Aux pattern will be hit by this, which I think it quite unfortunate for such widely used idioms.

If you don't think it's worth fixing here then I suggest deprecating the feature in favour of scalac's checking.

**Comment by matthewfarwell** [comment]
Fixed this by a documentation change. If you don't think the current documentation is clear enough, please say so.
