### ISSUE TITLE
Feature Request: Require Methods/Functions Called With Named Parameters

### ISSUE THREAD

**Issue by chrisdostert** [scalastyle/scalastyle#184]
**Feature Request**
To allow non-breaking parameter additions and increase readability, it is highly desirable to call Methods/Functions with named parameters. It would be awesome to have a scalastyle rule to enforce this behavior. 

**Examples of the benefits of calling methods/functions with named parameters**

allowing non-breaking parameter additions example

``` scala
// lets say MyCaseClass definition is changed to the following:
case class MyCaseClass(
  param1:String,
  newParam:String = "",
  param2:String,
  param3:String,
  param4:String
)

// would no longer compile
val unreadable = 
new MyCaseClass(
  "",
  "",
  "",
  ""
)

// would continue to compile
val readable = 
new MyCaseClass(
  param1="",
  param2="",
  param3="",
  param4=""
)
```

increased readability example 

``` scala
case class MyCaseClass(
  param1:String,
  param2:String,
  param3:String,
  param4:String
)

// difficult to differentiate between parameters
val unreadable = 
new MyCaseClass(
  "",
  "",
  "",
  ""
)

// easy to differentiate between parameters
val readable = 
new MyCaseClass(
  param1="",
  param2="",
  param3="",
  param4=""
)
```

**Comment by jawshooah** [comment]
Are you sure you want to require named parameters for *every argument* to *every single method call*, including calls into external APIs? That seems ridiculously over the top to me, and would end up making your code *less* readable due to the clutter.

**Comment by chrisdostert** [comment]
good point, how about allowing specifying included/excluded packages

**Comment by chrisdostert** [comment]
something like 
`includedPackagePatterns="com.myorg.*" `
`excludedPackagePatterns="com.myorg.adapters.*"`

**Comment by jawshooah** [comment]
That would require scalastyle to know which methods belong to which classes/objects, and which classes/objects belong to which packages, which is not remotely within scalastyle's capabilities. What you're looking for is a compiler plugin, or an IDE feature.

**Comment by chrisdostert** [comment]
Understood. So after sleeping on it the answer to your question is no different than if you had asked it for any other scalastyle rule. There may be code you don't want a rule applied on. In those cases you simply disable the rule surounding that code. In the event you find yourself turning a rule off too frequently in your codebase, it may not be a beneficial rule for your codebase.

**Comment by JohnDilley** [comment]
Though I believe this is useful for methods with long parameter lists (think data object constructors) I don't see it as useful for one and two parameter methods.  Rather than enforcing by package, possibly enforce by parameter list size, and make the cut-over between required/not required configurable.  Single argument methods don't need named parameters, 10 argument constructors do.  The cut-over is probably personal preference.

**Comment by chrisdostert** [comment]
@JohnDilley , if all it bought was readability I would agree about enforcing by parameter list size but it's intended to also ensure code gracefully handles parameter additions. Even a call with a single parameter will break if another parameter is added and it has been invoked without named parameters.

**Comment by jawshooah** [comment]
> Even a call with a single parameter will break if another parameter is added and it has been invoked without named parameters.

True, but if your method parameter lists are frequent points of code thrash, there's probably a deeper design flaw at play. In my experience, well-designed methods rarely require changes to their parameter lists, since they are small and focused on a single, narrowly defined purpose.

If you find your parameter list growing or changing too often, it's probably a sign that the method should be split up.

**Comment by chrisdostert** [comment]
In mature code sure, but in an agile environment with changing requirements. We're saying methods but this feature request covers case class constructors etc.. you can't know when business is going to want to add a few new attributes to models.

**Comment by jawshooah** [comment]
Fair enough, though that seems to lend support to @JohnDilley's point above:

> this is useful for methods with long parameter lists (think data object constructors)

Also note that your use case does not preclude enforcing by parameter list size. You'd just have to set the minimum size to 1, and everyone would be happy :tada:

**Comment by hussachai** [comment]
I think this feature is very useful. Otherwise, Scala would not adopt it. 
I'd like to give more examples in addition to what @chrisdostert already posted

**For example**
We have a PrintConfig case class that we use in many places in our code. The class defition is like the following.
```scala
case class PrintConfig(
   title: String, 
   body: String, 
   page: List[(Int, Int)] = Nil,
   color: Boolean = true,
   marginLeft: Int = 1, 
   marginRight: Int = 1, 
   marginTop: Int = 1,
   marginBottom: Int = 1
)
```
We normally don't use builder pattern to create a case class because it's immutable by default.
I mean we can do but it requires more work and we have to copy an object over and over.

At the moment, we can't do something like the following because scalacheck will complain
```scala
PrintConfig(title, body, marginTop = 4)
```
We have to do this
```scala
PrintConfig(title, body, Nil, true, 1, 1, 4, 1)
```
We have to repeat all the default values every time we construct this object which is not quite a good idea if those default values will be copied over and over all over the places. One day the company wants to cutback the cost of the ink and want us developers to change the default color value from true to false. We have to go over all the code and change the value from true to false. That's ok but how do we know that the method intends to use default value? document? test case? 

I know people can abuse this feature, but people still can abuse anything else. It's not good if they try to workaround the rule and introduce something even worse.

My suggestion is that why we don't have a configuration to turn it on or off or having a regex configuration. Don't have to be complex. The default configuration can be disabled if most people think it's bad.

**Comment by matthewfarwell** [comment]
If you are still interested in a Checker which checks for use of named parameters, a PR would be welcome.
