### ISSUE TITLE
Add a CyclomaticComplexityChecker option to ignore "case" keyword

### ISSUE THREAD

**Issue by tim-zh** [scalastyle/scalastyle#217]
It's a common case for complex domains and libraries (such as scalastyle) to have long lists of cases in `match` clauses, splitting them doesn't really simplify the code.

**Comment by matthewfarwell** [comment]
In this case you can always ignore the checker for this method, using // scalastyle:ignore or //scalastyle:on or off. Is this acceptable?

**Comment by dskrvk** [comment]
What's the rationale for discouraging long lists of `case` statements? Is this intentional or incidental to how the cyclomatic complexity checker is implemented? If intentional, what's the recommended alternative approach?

Turning off ScalaStyle for each large `match` statement is only a workaround, one that not only puts an extra burden on the writer, but also hides other potential issues in that block.
